### ISSUE TITLE
Soundness issue: writing to `addr_of!(arr)` is UB

### ISSUE THREAD

**Issue by RalfJung** [Qqwy/rust-overloaded_literals#2]
I stumbled upon the following code in this crate:

https://github.com/Qqwy/rust-overloaded_literals/blob/a136921bcf2d2c375736f8458841882ed9d5e56d/overloaded_literals/src/type_str.rs#L104-L109

That code is UB. `addr_of!(arr)` creates a read-only pointer and then later there is a write happening. That UB will likely in the future be detected by rustc so this code will then be rejected. (See [here](https://rust-lang.github.io/rfcs/3016-const-ub.html) for our policy around UB in `const`.)

There is currently no way to actually use `copy_nonoverlapping` in a `const`; that function got stabilized accidentally (and we are [debating](https://github.com/rust-lang/rust/pull/117905) whether to revert that stabilization, since it encourages misuse, such as what we are seeing in this crate).

As an alternative for this crate, you could use a loop that repeats `arr[i] = ...`; you don't actually need `copy_nonoverlapping` here I think.

**Comment by Qqwy** [comment]
Thank you very much for bringing this issue to my attention, and for your hard work on making Rust safer/more sound in general! I'll be following the revert-proposal with great interest.
